import type { Product } from './types';

// ============================================================
// Mock Product Data — works without Supabase
// ============================================================

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'mock-001',
    name: 'Vintage Floral Midi Dress',
    sku: 'KT-mock001',
    category: 'dresses',
    size: 'M',
    price: 1800,
    condition: 'Excellent',
    quantity: 1,
    measurements: { bust: '36"', waist: '28"', length: '42"' },
    description: 'Beautiful vintage floral midi dress with a flattering A-line silhouette. Features delicate floral print in warm tones, perfect for brunch or a garden party.',
    status: 'available',
    images: ['/images/cat-dresses.png'],
    sold_at: null,
    created_at: '2026-08-10T10:00:00Z',
    updated_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'mock-002',
    name: 'Silk Blend Wrap Top',
    sku: 'KT-mock002',
    category: 'tops',
    size: 'S',
    price: 1200,
    condition: 'New with tags',
    quantity: 2,
    measurements: { bust: '34"', length: '22"', shoulders: '14"' },
    description: 'Luxurious silk-blend wrap top in a rich emerald green. New with tags — never worn. Adjustable tie at the waist.',
    status: 'available',
    images: ['/images/cat-tops.png'],
    sold_at: null,
    created_at: '2026-08-09T14:30:00Z',
    updated_at: '2026-08-09T14:30:00Z',
  },
  {
    id: 'mock-003',
    name: 'High-Waist Levi\'s 501 Jeans',
    sku: 'KT-mock003',
    category: 'jeans',
    size: '28',
    price: 2500,
    condition: 'Good',
    quantity: 1,
    measurements: { waist: '28"', hips: '38"', inseam: '30"', length: '40"' },
    description: 'Classic Levi\'s 501 high-waist jeans with a lived-in fade. True vintage denim with character.',
    status: 'available',
    images: ['/images/cat-jeans.png'],
    sold_at: null,
    created_at: '2026-08-08T09:15:00Z',
    updated_at: '2026-08-08T09:15:00Z',
  },
  {
    id: 'mock-004',
    name: 'Leather Ankle Boots',
    sku: 'KT-mock004',
    category: 'shoes',
    size: '38',
    price: 3200,
    condition: 'Excellent',
    quantity: 1,
    measurements: {},
    description: 'Genuine leather ankle boots with a stacked heel. Minimal wear, excellent condition. Perfect for the Nairobi cool season.',
    status: 'available',
    images: ['/images/cat-shoes.png'],
    sold_at: null,
    created_at: '2026-08-07T16:45:00Z',
    updated_at: '2026-08-07T16:45:00Z',
  },
  {
    id: 'mock-005',
    name: 'Vintage Leather Crossbody Bag',
    sku: 'KT-mock005',
    category: 'bags',
    size: 'One Size',
    price: 2800,
    condition: 'Good',
    quantity: 1,
    measurements: {},
    description: 'Beautiful vintage leather crossbody bag with brass hardware. Aged patina adds character. Adjustable strap, multiple compartments.',
    status: 'available',
    images: ['/images/cat-bags.png'],
    sold_at: null,
    created_at: '2026-08-06T11:20:00Z',
    updated_at: '2026-08-06T11:20:00Z',
  },
  {
    id: 'mock-006',
    name: 'Chunky Gold Chain Necklace',
    sku: 'KT-mock006',
    category: 'accessories',
    size: 'One Size',
    price: 950,
    condition: 'New with tags',
    quantity: 3,
    measurements: {},
    description: 'Statement chunky gold chain necklace. Brand new with tags. Goes with everything from a plain tee to a cocktail dress.',
    status: 'available',
    images: ['/images/cat-accessories.png'],
    sold_at: null,
    created_at: '2026-08-05T08:00:00Z',
    updated_at: '2026-08-05T08:00:00Z',
  },
  {
    id: 'mock-007',
    name: 'Pleated Satin Maxi Dress',
    sku: 'KT-mock007',
    category: 'dresses',
    size: 'L',
    price: 3500,
    condition: 'Excellent',
    quantity: 1,
    measurements: { bust: '40"', waist: '32"', length: '54"', hips: '42"' },
    description: 'Stunning pleated satin maxi dress in deep burgundy. Perfect for weddings and formal events. Flows beautifully when you walk.',
    status: 'available',
    images: ['/images/cat-dresses.png'],
    sold_at: null,
    created_at: '2026-08-04T13:10:00Z',
    updated_at: '2026-08-04T13:10:00Z',
  },
  {
    id: 'mock-008',
    name: 'Oversized Denim Jacket',
    sku: 'KT-mock008',
    category: 'tops',
    size: 'L',
    price: 2200,
    condition: 'Good',
    quantity: 1,
    measurements: { bust: '44"', length: '26"', shoulders: '18"' },
    description: 'Classic oversized denim jacket with a perfect vintage wash. Layer over dresses or wear with jeans for a Canadian tuxedo moment.',
    status: 'available',
    images: ['/images/cat-tops.png'],
    sold_at: null,
    created_at: '2026-08-03T17:30:00Z',
    updated_at: '2026-08-03T17:30:00Z',
  },
  {
    id: 'mock-009',
    name: 'White Canvas Sneakers',
    sku: 'KT-mock009',
    category: 'shoes',
    size: '40',
    price: 1500,
    condition: 'Good',
    quantity: 2,
    measurements: {},
    description: 'Clean white canvas sneakers, lightly worn. A wardrobe essential that pairs with everything.',
    status: 'available',
    images: ['/images/cat-shoes.png'],
    sold_at: null,
    created_at: '2026-08-02T09:45:00Z',
    updated_at: '2026-08-02T09:45:00Z',
  },
  {
    id: 'mock-010',
    name: 'Woven Straw Tote Bag',
    sku: 'KT-mock010',
    category: 'bags',
    size: 'One Size',
    price: 1800,
    condition: 'New with tags',
    quantity: 1,
    measurements: {},
    description: 'Handwoven straw tote bag with leather handles. New with tags. Perfect for the beach or weekend market runs.',
    status: 'available',
    images: ['/images/cat-bags.png'],
    sold_at: null,
    created_at: '2026-08-01T12:00:00Z',
    updated_at: '2026-08-01T12:00:00Z',
  },
  {
    id: 'mock-011',
    name: 'Slim Fit Stretch Jeans',
    sku: 'KT-mock011',
    category: 'jeans',
    size: '30',
    price: 1900,
    condition: 'Excellent',
    quantity: 1,
    measurements: { waist: '30"', hips: '40"', inseam: '32"', length: '42"' },
    description: 'Dark wash slim fit jeans with comfortable stretch. Barely worn, in excellent condition.',
    status: 'available',
    images: ['/images/cat-jeans.png'],
    sold_at: null,
    created_at: '2026-07-31T15:20:00Z',
    updated_at: '2026-07-31T15:20:00Z',
  },
  {
    id: 'mock-012',
    name: 'Beaded Statement Earrings',
    sku: 'KT-mock012',
    category: 'accessories',
    size: 'One Size',
    price: 650,
    condition: 'New with tags',
    quantity: 4,
    measurements: {},
    description: 'Handmade beaded statement earrings in vibrant earth tones. Locally crafted, lightweight, and eye-catching.',
    status: 'available',
    images: ['/images/cat-accessories.png'],
    sold_at: null,
    created_at: '2026-07-30T10:30:00Z',
    updated_at: '2026-07-30T10:30:00Z',
  },
];

/**
 * Check if Supabase is properly configured.
 */
export function isSupabaseConfigured(): boolean {
  const url = import.meta.env.VITE_SUPABASE_URL;
  const key = import.meta.env.VITE_SUPABASE_ANON_KEY;
  return !!(url && key && !url.includes('placeholder') && !key.includes('placeholder'));
}
