import fs from 'node:fs';
import path from 'node:path';
import { createClient } from '@supabase/supabase-js';
import crypto from 'node:crypto';

// The directory containing the user's real images
const IMAGES_DIR = 'C:\\Users\\wanji\\OneDrive\\Pictures\\KAELTHRIFT S';

// Ensure the user has provided the environment variables
const SUPABASE_URL = process.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = process.env.VITE_SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('❌ Error: Missing VITE_SUPABASE_URL or VITE_SUPABASE_SERVICE_ROLE_KEY environment variables.');
  console.error('Please run this script with your environment variables set, e.g.:');
  console.error('$env:VITE_SUPABASE_URL="https://..."; $env:VITE_SUPABASE_SERVICE_ROLE_KEY="ey..."; node scripts/seed_products.mjs');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

// Helper to generate a random price between 500 and 5000 KES
function getRandomPrice() {
  return Math.floor(Math.random() * 45 + 5) * 100; 
}

// Categories and conditions to randomly assign
const CATEGORIES = ['dresses', 'tops', 'jeans', 'shoes', 'bags', 'accessories'];
const CONDITIONS = ['New with tags', 'Excellent', 'Good'];
const SIZES = ['XS', 'S', 'M', 'L', 'XL', 'Free Size'];

async function seedProducts() {
  console.log('🚀 Starting KaelThrift product seeding process...');
  
  if (!fs.existsSync(IMAGES_DIR)) {
    console.error(`❌ Error: Directory not found -> ${IMAGES_DIR}`);
    process.exit(1);
  }

  const files = fs.readdirSync(IMAGES_DIR).filter(file => 
    file.toLowerCase().endsWith('.jpg') || 
    file.toLowerCase().endsWith('.jpeg') || 
    file.toLowerCase().endsWith('.png')
  );

  console.log(`📸 Found ${files.length} images to upload and process.`);

  let successCount = 0;

  for (let i = 0; i < files.length; i++) {
    const fileName = files[i];
    const filePath = path.join(IMAGES_DIR, fileName);
    
    console.log(`\nProcessing (${i + 1}/${files.length}): ${fileName}`);

    try {
      // 1. Upload Image to Supabase Storage
      const fileBuffer = fs.readFileSync(filePath);
      const fileExtension = path.extname(fileName);
      const uniqueFileName = `${crypto.randomUUID()}${fileExtension}`;
      
      const { data: uploadData, error: uploadError } = await supabase.storage
        .from('product-images')
        .upload(`seed/${uniqueFileName}`, fileBuffer, {
          contentType: `image/${fileExtension.substring(1)}`,
          upsert: true
        });

      if (uploadError) {
        console.error(`   ❌ Failed to upload image:`, uploadError.message);
        continue;
      }

      // Get public URL for the uploaded image
      const { data: { publicUrl } } = supabase.storage
        .from('product-images')
        .getPublicUrl(`seed/${uniqueFileName}`);

      // 2. Create Product Entry in Database
      const randomCategory = CATEGORIES[Math.floor(Math.random() * CATEGORIES.length)];
      const randomCondition = CONDITIONS[Math.floor(Math.random() * CONDITIONS.length)];
      const randomSize = SIZES[Math.floor(Math.random() * SIZES.length)];
      
      const productData = {
        name: `Premium Thrifted Item #${i + 1}`,
        category: randomCategory,
        size: randomSize,
        price: getRandomPrice(),
        condition: randomCondition,
        quantity: 1,
        status: 'available',
        description: 'Autogenerated description for premium thrifted piece. Actual details may vary.',
        images: [publicUrl],
        measurements: {}
      };

      const { error: dbError } = await supabase
        .from('products')
        .insert(productData);

      if (dbError) {
        console.error(`   ❌ Failed to insert product into DB:`, dbError.message);
      } else {
        console.log(`   ✅ Successfully created product!`);
        successCount++;
      }

    } catch (err) {
      console.error(`   ❌ Unexpected error processing ${fileName}:`, err);
    }
  }

  console.log(`\n🎉 Seeding complete! Successfully created ${successCount}/${files.length} products.`);
}

seedProducts();
